#!/usr/bin/env zsh
git submodule init
git submodule update --recursive
files=( 'zshrc' 'bashrc' 'vimrc' 'vim' 'tmux.conf' 'profile' 'scripts' )
for file in $files
do
    echo ""
    if [ -e "$HOME/.${file}" ]
    then
        echo "Moving current .${file}"
        mv -iv "$HOME/.${file}" "$HOME/${file}_$(date +%s)"
    fi
    echo "Simlinking ${file} to $HOME"
    ln -s "$PWD/${file}" "$HOME/.${file}"
    if [ $? -eq 0 ]; then
        echo "$PWD/${file} ~> $HOME/.${file}"
    else
        echo 'Install failed to symlink. See GitHub.com/BrandonRoehl/dotfiles for help'
        exit 1
    fi
done

if [ hash brew >/dev/null 2>&1 ]; then
    echo 'Attempting to install brew'
    if [ uname = "Darwin" ]; then
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    else
        sudo apt-get install build-essential curl git python-setuptools ruby
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
    fi
fi
brew install coreutils vim tmux wget bash

echo 'install rvm or upgrade rvm'
\curl -sSL https://get.rvm.io | bash -s stable
