#!/bin/sh
git submodule init
git submodule update --recursive
files=( "zshrc" "bashrc" "vimrc" "vim" "tmux.conf" "profile" )
for file in files
do
    echo ""
    if [ -e "$HOME/.${i}" ]
    then
        echo "Moving current .${i}"
        mv -iv "$HOME/.${i}" "$HOME/${i}_$(date +%s)"
    fi
    echo "Simlinking ${i} to $HOME"
    ln -s "$PWD/${i}" "$HOME/.${i}"
    if [ $? -eq 0 ]; then
        echo "$PWD/${i} ~> $HOME/.${i}"
    else
        echo 'Install failed to symlink. See GitHub.com/BrandonRoehl/dotfiles for help'
        exit 1
    fi
done

if [ hash brew >/dev/null 2>&1 ]; then
    echo 'Attempting to install brew'
    if [ uname = "Darwin" ]; then
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    else
        sudo apt-get install build-essential curl git python-setuptools ruby
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
    fi
fi
brew install coreutils vim tmux wget bash

echo 'install rvm or upgrade rvm'
\curl -sSL https://get.rvm.io | bash -s stable
