#!/bin/bash
echo '      _       _    __ _ _'
echo '   __| | ___ | |_ / _(_) | ___  ___'
echo '  / _` |/ _ \| __| |_| | |/ _ \/ __|'
echo ' | (_| | (_) | |_|  _| | |  __/\__ \'
echo '(_)__,_|\___/ \__|_| |_|_|\___||___/'
git submodule init
git submodule update --recursive
files=( 'vimrc' 'vim' 'zshrc' 'zsh' 'tmux.conf' 'bashrc' 'profile' 'atom' )
for file in ${files[@]}
do
    echo ""
    if [ -e "$HOME/.$file" ]
    then
        if [ -h "$HOME/.$file" ] && [ $(readlink "$HOME/.$file") = "$PWD/$file" ]
        then
            rm "$HOME/.$file"
        else
            echo "Moving current .$file"
            mv -ivf "$HOME/.$file" "$HOME/${file}_$(date +%s)"
        fi
    fi
    echo "Simlinking $file to $HOME"
    ln -s "$PWD/$file" "$HOME/.$file"
    if [ $? -eq 0 ]
    then
        echo "$PWD/$file ~> $HOME/.$file"
    else
        echo 'Install failed to symlink. See GitHub.com/BrandonRoehl/dotfiles for help'
        exit 1
    fi
done
git config --global alias.l 'log --graph --decorate --all'

if [ hash brew >/dev/null 2>&1 ]
then
    echo 'Attempting to install brew'
    if [ uname = "Darwin" ]
    then
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    else
        sudo apt-get install build-essential curl git python-setuptools ruby
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
    fi
fi
brew install coreutils vim tmux wget bash

echo 'install rvm or upgrade rvm'
curl -sSL https://get.rvm.io | bash -s stable
if [ hash rvm >/dev/null 2>&1 ]
then
    rvm cleanup all
fi
