#!/bin/sh
# Shell script to compile run and remove the files with gcc
for file in $@
do
    raw="${file/.c/}_$(md5sum $file | awk '{print $1}')"
    if ! [[ $raw =~ '^\.' ]]
    then
        raw=".$raw"
    fi
    gcc -std=gnu99 $file -o ./$raw && ./$raw
    if [ -e ./$raw ]
    then
        rm ./$raw
    fi
done
