#!/bin/sh
echo 'Updating git repositories for vim pathogen plugins'
currentPath=$PWD
dotdir=$(readlink ~/.scripts)
cd ${dotdir/\/scripts/}
git submodule foreach \
        '
        git clean -fdx;
        git reset --hard;
        git checkout master -f;
        git pull origin master -f;
        '
cd $currentPath
