#!/bin/sh
## FF ## First thing I ever wrote in shell and the first thing to make it's way
# to my bash profile show and hide hidden files on mac os x
current_value=$(defaults read com.apple.finder AppleShowAllFiles)
if [ $current_value = TRUE ]
then
    echo 'Files are now hidden'
    defaults write com.apple.finder AppleShowAllFiles FALSE
else
    echo 'Files are now visible'
    defaults write com.apple.finder AppleShowAllFiles TRUE
fi
killall Finder
